export const constants = {
    DISPLAY_NAME_MIN_LENGTH: 3,
    DISPLAY_NAME_MAX_LENGTH: 100,
    EMAIL_MIN_LENGTH: 4,
    EMAIL_MAX_LENGTH: 100,
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 256,
}
