const enum Css {
  ASYMMETRIC_COLOR = 'asymmetric-color',
  BUTTON = 'button',
  COL_2 = 'col-2',
  CONTENT_CLOSE = 'content-close',
  CONTENT_MENU = 'content-menu',
  FOOTER_LINK = 'footer-link',
  GRID_FORM = 'grid-form',
  GRID_FORM_ROW_2 = 'grid-row-2',
  GRID_FORM_ROW_4 = 'grid-row-4',
  GRID_FORM_ROW_6 = 'grid-row-6',
  HIDDEN = 'hidden',
  ICON_FONT = 'icon-font',
  LOGO = 'logo',
  MENU_LINK = 'menu-link',
  MOBILE_MENU_SYMBOL = 'mobile-menu-symbol',
  NAVBAR = 'navbar',
  RADIO = 'radio',
  SUBMIT = 'submit',
  SYMMETRIC_COLOR = 'symmetric-color',
  TEXT = 'text',
  TEXT_CENTER = 'text-center',
  TEXTAREA_CONTAINER = 'textarea-container',
  SIDE_MENU_LANGUAGE = 'side-menu-language',
  SIDE_MENU_THEME = 'side-menu-theme',
  SIDE_MENU = 'side-menu',
  THEME_LIGHT = 'light',
  THEME_DARK = 'dark',
  WELCOME = 'welcome',
}

export default Css;
