version: "3"
services:
  sass:
    image: node:lts
    container_name: sass_c
    volumes:
      - ./:/home/app
      - /home/app/node_modules
    working_dir: /home/app
    command: /bin/bash -c "npm install && npm run build"
