name: Miracle Hides Tabletop
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'id_token'
          workload_identity_provider: '${{ secrets.gcloud_workload_identity_provider }}'
          service_account: '${{ secrets.gcloud_service_account }}'
          id_token_audience: '${{ secrets.gcloud_workload_identity_provider }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: 'gcloud run deploy miracle-hides-tabletop --source miracle-hides-tabletop --allow-unauthenticated --description="tabletop games" --region=us-central1 --port=3000 --service-account=${{ secrets.GCLOUD_MHT_SERVICE_ACCOUNT }}'
