name: Miracle Hides Keys
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: prepare deployment
        run: npm run github
        working-directory: miracle-hides-keys
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/962188365368/locations/global/workloadIdentityPools/github/providers/GithubProvider'
          service_account: 'githubactions@miracle-hides.iam.gserviceaccount.com'
          token_format: 'access_token'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: 'gcloud run deploy miracle-hides-keys --source miracle-hides-keys/src-server-nest --allow-unauthenticated --description="encryption service"'

