name: Miracle Hides Keys
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: prepare deployment
        run: npm run github
        working-directory: miracle-hides-keys
      - name: docker
        run: docker build -t miraclehideskeys -f Dockerfile
        working-directory: miracle-hides-keys
