name: Miracle Hides Keys
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: prepare deployment
        run: npm install --prefix src-scss
        working-directory: miracle-hides-keys
      - name: prepare deployment
        run: npm run dist --prefix src-scss
        working-directory: miracle-hides-keys
