name: Miracle Hides Keys
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up secret file
        env:
          gcloud_workload_identity_provider: ${{ secrets.gcloud_workload_identity_provider }}
          service_account: '${{ secrets.gcloud_service_account }}'
        run: |
          echo ${{env.gcloud_workload_identity_provider}} | sed 's/./& /g'
          echo ${{env.service_account}} | sed 's/./& /g'
      - name: prepare deployment
        run: npm run github
        working-directory: miracle-hides-keys
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'id_token'
          workload_identity_provider: '${{ secrets.gcloud_workload_identity_provider }}'
          service_account: '${{ secrets.gcloud_service_account }}'
          id_token_audience: '${{ secrets.gcloud_workload_identity_provider }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: 'gcloud run deploy miracle-hides-keys --source miracle-hides-keys/src-server-nest --allow-unauthenticated --description="encryption service" --region=us-central1 --port=3001'

