class DeTranslator extends BaseTranslator {
  constructor() {
    super(
      'de', 
      {
        email: 'E-Mail',
        emailPlaceholder: 'deine-email@deine-domain.example',
        password: 'Passwort',
        passwordPlaceholder: 'foo123%6&§HG',
        passwordRepeat: 'Passwort wiederholden',
        passwordRepeatPlaceholder: 'Passwort wiederholen',
        signInHeadline: 'Willkommen zurück!',
        signInSubmit: 'Anmelden',
        signIn401: 'Unbekannte Kombination aus Benutzernamen und Passwort',
        signInLinkToSignUp: 'Ich habe noch keinen Account',
        messengerHeadline: 'Miracle Hides',
        signUpHeadline: 'Willkommen bei Miracle Hides',
        signUpSubmit: 'Anmelden',
        signUpLinkToSignIn: 'Ich habe bereits einen Account',
        guidPlaceholder: 'a4856786-e7c2-4183-a16e-002b1688b0fa',
        invitationCode: 'Einladungscode',
        displayName: 'Benutzername',
        displayNamePlaceholder: 'deine Name',
        messengerCreateChat: 'Neuer Chat',
        messengerCreateChatHeadline: 'Neuer Chat',
        messengerCreateChatSubmit: 'Anlegen',
        messengerCreateChatEmail: 'Chat Partner',
        messengerCreateChatEmailPlaceholder: 'sein_name@seine_domain.example',
        messengerCreateChatInvitation: 'Add chat invitation',
        messengerCreateChatInvitationKeySize: 'RSA Schlüssellänge',
        messengerCreateChatInvitationPublicKey: 'Öffentlicher Schlüssel',
        messengerCreateChatInvitationPrivateKey: 'Privater Schlüssel',
        messengerCreateChatInvitationCreateKeys: 'Keys generieren',
        messengerCreateChatInvitationCopy: 'kopieren',

        messengerCreateChatInvitationNext: 'Weiter',
        messengerCreateChatInvitationPrevious: 'Zurück',
        messengerCreateChatInvitationReceiverHeadline: 'Chat-Partner',
        messengerCreateChatInvitationReceiverText: 'An wen soll die Einladung gesendet werden? Der Text ist frei wählbar und wird zukünftig zur Anzeige in Chats verwendet.',
        messengerCreateChatInvitationReceiverReceiver: 'Empfänger',
        messengerCreateChatInvitationReceiverReeiverPlaceholder: 'Wer soll eingeladen werden?',

        createChatInvitationPage_headline: 'Neue Chat Einladung',
        createChatInvitationPage_next: 'Weiter',
        createChatInvitationPage_nextFinal: 'Abschließen',
        createChatInvitationPage_previous: 'Zurück',
        createChatInvitationPage_receiver: 'Empfänger',
        createChatInvitationPage_receiverPlaceholder: 'Wer soll die Einladung erhalten?',
        createChatInvitationPage_receiverText: 'An wen soll die Chat-Einladung gesendet werden? Der Name wird zukünftig im Chat verwendet.',
      
        createChatInvitationPage_keysText: 'Generiere privaten und öffentlichen Schlüssel zur Versendung von Nachrichten. Die Schlüssel können nur für einen Chat-Partner verwendet werden.',
        createChatInvitationPage_keysSize: 'Länge des Schlüssels',
        createChatInvitationPage_keysPrivate: 'Privater Schlüssel',
        createChatInvitationPage_keysPrivatePlaceholder: 'Privaten Schlüssel generieren oder hier eingeben.',
        createChatInvitationPage_keysPublic: 'Öffentlicher Schlüssel',
        createChatInvitationPage_keysPublicPlaceholder: 'Öffentlichen Schlüssel generieren oder hier eingeben.',
        createChatInvitationPage_keysGenerate: 'Schlüssel generieren',
        createChatInvitationPage_keysMismatch: 'Privater und öffentlicher Schlüssel passen nicht zusammen.',
        createChatInvitationPage_addKeysText: 'Bitte kopieren Sie die Schüsseldaten in die Zwischenablage und sichern die Daten an einem sichern Ort. Die Daten benötigen Sie bei jedem Neustart des Programms und ersetzen die bisherigen Schlüsseldaten. Fahren Sie erst fort, wenn die Daten gesichert wurden.',
        createChatInvitationPage_addKeysCopy: 'In Zwischenablage kopieren',
        createChatInvitationPage_sendKeysText: 'Kopieren Sie den Schlüssel und versenden sie diesen per Email, Brief, Pony-Reiter an den Empfänger',
        createChatInvitationPage_sendKeysCopy: 'In die Zwischenablage kopieren',
      },
    );
  }
}
